### PR TITLE
Merging dev to main

### PR DESCRIPTION
**Pull request by WebDevMcFarland**
Merging all changes into main for backup on presentation

### CODE REVIEW

**Review by DanielGaran02 — APPROVED** [review]
Everything looks great

**Review by tori-obregon — APPROVED** [review]
Confirming this is a working version to present today

**Review by anthonyHerr — APPROVED** [review]
great work team!

**Review by josuerole — APPROVED** [review]
This looks good our MVP is pretty much done!

**Comment by josuerole** [comment]
This looks good our MVP is pretty much done!

**Pull request merged**
